this.gbar_=this.gbar_||{};(function(_){var window=this;
try{
var wx=[1],xx=function(a){_.F(this,a,"gaia.l.a.r",-1,wx)};_.y(xx,_.E);xx.b="gaia.l.a.r";var yx=function(a){_.F(this,a,"gaia.l.a",-1,null)};_.y(yx,_.E);yx.b="gaia.l.a";var zx=function(a){_.F(this,a,0,-1,null)};_.y(zx,_.E);var Ax=function(a){_.F(this,a,0,-1,null)};_.y(Ax,_.E);
var Bx=function(a){var c=_.t(a)?a.split(""):a;for(a=a.length-1;0<=a;a--)if(a in c&&_.Ao.call(void 0,c[a]))return a;return-1},Cx=function(a,c){var d={},e;for(e in a)c.call(void 0,a[e],e,a)&&(d[e]=a[e]);return d},Dx=function(a){this.ja=a;this.b={}};Dx.prototype.Qa=function(){var a=Cx(this.b,function(a){return null!==a}),a=_.vi(a)?null:a,a=[this.ja,this.o,a],c=Bx(a);return a=a.slice(0,c+1)};Dx.prototype.toString=function(){var a=this.Qa();return"("+(0,_.Ca)(a,function(a){return _.Gb(a)}).join(",")+")"};
Dx.prototype.getId=function(){return this.ja};var Ex=function(){Dx.call(this,"web")};_.y(Ex,Dx);var Fx=function(){Dx.call(this,"video-search")};_.y(Fx,Dx);var Gx=function(){Dx.call(this,"url")};_.y(Gx,Dx);var Hx=function(){Dx.call(this,"photos")};_.y(Hx,Dx);var Ix=function(){Dx.call(this,"maps")};_.y(Ix,Dx);var Jx=function(){Dx.call(this,"image-search")};_.y(Jx,Dx);
var Kx=function(a,c){var d={},e;for(e in a)d[e]=c.call(void 0,a[e],e,a);return d},Lx=function(a){this.o=_.t(a)?new Dx(a):a;this.b=[];this.w={}},Mx=function(a){switch(a){case "image-search":return new Jx;case "maps":return new Ix;case "photos":return new Hx;case "url":return new Gx;case "video-search":return new Fx;case "web":return new Ex}return new Dx(a)},Nx=function(a){return"("+(0,_.Ca)(a.b,function(a){return a.toString()}).join(",")+")"},Ox=function(a){a=Cx(a.w,function(a){return null!==a});return(a=
_.vi(a)?null:a)?_.Gb(Kx(a,function(a){return a.toString()})):""};Lx.prototype.toString=function(){if(this.o){var a=["{root:",this.o.toString(),",items:",Nx(this)],c=Ox(this);c&&(a.push(",options:"),a.push(c));a.push("}");return a.join("")}return Nx(this)};var Px=function(a){return eval("("+a+")")},Qx=function(a){this.A=a||"https://docs.google.com/picker";this.o=new Lx};Qx.prototype.o=null;var Rx=function(a,c){a.o.b.push(_.t(c)?Mx(c):c);return a},Sx=function(){};_.y(Sx,Error);
var Tx=/.*?\/(\d{6,})\/(?:\1\/)*(.*\/?)/,Ux=function(a){Qx.call(this,a)};_.y(Ux,Qx);var Vx=function(a,c,d,e,f){_.Ap.call(this,a,e);this.C=f;this.F=this.b.getAttribute("data-pid");this.B=c;this.o=d;_.Co(this,this.b,_.ql,(0,_.u)(this.D,this));if(a=_.W("gb_3",this.b))a=a.style.backgroundPosition.split(" "),_.zp("#"+this.b.id+" .gb_3::before{left:"+a[0]+";top:"+a[1]+"}")};_.y(Vx,_.Ap);
Vx.prototype.D=function(a){var c=a.o;if(_.di(c,"gb_0"))a.preventDefault(),a.stopPropagation();else{a={t:this.F,l:this.B};if(c){var d=c.getAttributeNode("data-ved");d&&d.value&&(a.ved=d.value);_.di(c,"gbpq")&&Wx(this,c)}this.C.log(1,a)}};
var Wx=function(a,c){if(a.o)window.b&&_.yp(c,window.b.aj(c.href));else if(window.document.forms[0]&&window.document.forms[0].q){var d=(window.document.forms[0].q||"").value;d&&_.yp(c,c.href.replace(/([?&])q=[^&]*|$/,function(a,c){return(c||"&")+"q="+(0,window.encodeURIComponent)(d)}))}else a.w.log(new Sx)},Xx=function(a,c,d,e,f,g){_.z.call(this);this.o=a;this.B=d;this.D=c;this.F=e;this.A=g;this.w=new _.dp(f,this);this.b=_.og("op");this.w.L(this.b,"message",this.C)};_.y(Xx,_.z);
Xx.prototype.O=function(){Xx.J.O.call(this);delete this.o;delete this.B;this.w.fa()};Xx.prototype.H=function(a){var c=this.b.b.b;c&&(c=_.vp(c))&&(_.tp(c,a),a&&this.A.log(34))};Xx.prototype.C=function(a){a=a.w[0];if("picked"==a.action){a=a.docs[0].thumbnails;var c=Yx(a,this.D);c&&(this.o.style.backgroundImage="url("+c+")");if(a=Yx(a,this.F))this.B.style.backgroundImage="url("+a+")";this.A.log(35)}};
var Yx=function(a,c){for(var d=0;d<a.length;d++)if(a[d].height==c)return a[d].url;return null},$x=function(a){Qx.call(this,a);this.b=new _.Pf(this.A);Zx(this,"gadgets");(a=window.location.origin)||(a=window.location.protocol+"//"+window.location.host);a&&_.dg(this.b,"origin",a);this.w=[]};_.y($x,Ux);$x.prototype.getHeight=function(){return this.B};
var Zx=function(a,c){_.dg(a.b,"protocol",c);return a},ay=function(a){a.w.length&&_.dg(a.b,"pp",_.Gb(a.w));return _.dg(a.b,"nav",Nx(a.o)).clone()},by=function(a,c,d,e,f){_.z.call(this);this.F=e;this.ca=f;this.b=_.W("gb_Cb",a);this.A=_.W("gb_Nb",a);this.M=_.K(_.G(c,23));this.P=_.L(_.G(c,20));this.K=_.L(_.G(c,16));this.ha=new _.dp(e,this);this.N=_.L(_.G(c,1));this.T=_.L(_.G(c,4));this.G=_.L(_.G(c,2));this.Z=_.L(_.G(c,24));this.ka=_.K(_.G(c,3));this.da=_.K(_.G(c,22));this.W=_.K(_.G(c,5));this.B=_.L(_.G(c,
13));this.X=_.L(_.G(d,6));this.ba=_.L(_.G(d,7));this.H=_.L(_.G(c,8));this.$=_.G(c,21)||this.H;this.Ea=_.L(_.G(c,25));this.o=[];this.w={};a=_.dq("gb_Db",this.b);for(d=0;d<a.length;d++)if(f=_.W("gb_Lb",a[d]),e=_.W("gb_Jb",a[d]),f&&e){if(_.pc&&null!==f&&"innerText"in f)f=f.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var g=[];_.to(f,g,!0);f=g.join("")}f=f.replace(/ \xAD /g," ").replace(/\xAD/g,"");f=f.replace(/\u200B/g,"");_.pc||(f=f.replace(/ +/g," "));" "!=f&&(f=f.replace(/^\s*/,""));this.w[f]=e.getAttribute("data-src")||
e.src}this.D=!1;this.C=_.K(_.G(c,14));this.V=_.L(_.G(c,15))};_.y(by,_.z);by.prototype.O=function(){by.J.O.call(this);delete this.b;delete this.A;this.o=null;this.ha.fa()};
var ey=function(a){_.Nh(a.b,_.uc);a.o=[];cy(a);dy(a,!1)},fy=function(a,c){var d=c.Ya;c.Me?d=a.N.replace("%1$s",c.Ya):c.Ne?d=a.T.replace("%1$s",c.Ya):2==c.type&&(d=a.G);var e=2==c.type?c.Ya:d,f=c.$e;f?a.w[e]=f:f=a.w[e]?a.w[e]:1==c.type?"//ssl.gstatic.com/gb/images/silhouette_48.png":"//ssl.gstatic.com/gb/images/pluspages_48.png";e="gb_Jb";a.M&&(e+=" gb_sb");f=_.R("IMG",{"class":e,src:f,alt:2==c.type?a.K:a.P});e=_.R("DIV","gb_Kb",c.name||c.Ya);d=_.R("DIV","gb_Lb",d);d=[e,d];c.zd&&(e=_.R("DIV","gb_Mb",
a.Z),d.push(e));var d=_.R("DIV","gb_Fb",d),e={"class":"gb_Db"},g=c.Dd;if(g){if(a.C&&2==c.type){var h=c.id,l=g.match(Tx);if(l)var h=h||l[1],q=l[2],r=window.location.href,g=(l=r.match(Tx))?r.replace(new RegExp(l[1],"g"),h):g.replace(q,a.V)}e.href=g}if(g=(g=1==c.type?a.ka:a.da)||a.C&&2==c.type)e.target="_blank",_.Cb&&(e.rel="noreferrer");f=_.R("A",e,[f,d]);c.Le&&((a=_.W("gb_Hb",a.b))&&_.U(a,"gb_Hb"),_.V(f,"gb_Hb"));return f},gy=function(a,c,d){a.b.appendChild(c);a.o.push(c);cy(a);2==d&&dy(a,!0)},dy=
function(a,c){_.gq(a.A,"gb_7a",!c);a.A.setAttribute("aria-hidden",!c+"")},cy=function(a){var c=a.b.children.length,c=0==c||1==c&&_.di(a.b.firstChild,"gb_Hb");_.gq(a.b,"gb_7a",c);a.b.setAttribute("aria-hidden",c+"")},hy=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
by.prototype.Y=function(a){a=a.b;var c=a.origin,d=this.B.match(_.Ie),c=c.match(_.Ie);if(d[3]==c[3]&&d[1]==c[1]&&d[4]==c[4])try{var e;a:{try{e=_.kg(new xx(Px(a.data)),yx,1);break a}catch(Io){}e=null}if(e&&0<e.length)for(ey(this),a=0;a<e.length;++a){var f,g=e[a],d={valid:!1};if(g){d.type=_.G(g,1);d.Ya=_.L(_.G(g,3));d.Me=_.K(_.G(g,6));d.zd=_.K(_.G(g,14));d.Ne=!1;d.name=_.L(_.G(g,2));d.id=_.L(_.G(g,10));d.$e=_.L(_.G(g,4));var h=_.G(g,7),l=null!=h?h.toString():"",q=1==d.type,r=q?"none":d.id;d.Le=q?this.X==
d.Ya:this.ba==r;var v=(q?this.H:this.$).replace("$authuser",l).replace("$session_index",l).replace("$pageId",r).replace("$email",d.Ya);if(d.zd){var H=new _.Pf(hy()),P=new _.Pf(v),La=H.clone(),ea=!!P.A;ea?_.Qf(La,P.A):ea=!!P.D;ea?La.D=P.D:ea=!!P.o;ea?_.Rf(La,P.o):ea=null!=P.F;var Aa=P.w;if(ea)_.Sf(La,P.F);else if(ea=!!P.w){if("/"!=Aa.charAt(0))if(H.o&&!H.w)Aa="/"+Aa;else{var Yb=La.w.lastIndexOf("/");-1!=Yb&&(Aa=La.w.substr(0,Yb+1)+Aa)}Aa=_.yo(Aa)}ea?_.Tf(La,Aa):ea=""!==P.b.toString();ea?_.Uf(La,P.b.clone()):
ea=!!P.B;ea&&(La.B=P.B);d.Dd=this.Ea.replace("$continue",_.id(La.toString())).replace("$email",_.id(d.Ya))}else d.Dd=v;d.valid=!0}f=d;if(f.valid){var Jf=fy(this,f);gy(this,Jf,f.type)}}}catch(Io){this.F.log(Io)}};var iy=function(a,c){Dx.call(this,"webcam");a&&(this.b.type=a);c&&(this.b.query=c)};_.y(iy,Dx);var jy=function(a){Dx.call(this,"upload");this.b.query=a};_.y(jy,Dx);
var ky=function(a,c,d,e,f){for(var g=[],h=0;h<a.length;h++)g.push(new Vx(a[h],c,d,e,f));return g},ly=function(a,c,d,e,f,g){this.C=c;this.P=d;_.Rp.call(this,a,"gbd4",e,f,!0,g);this.ta=this.G=5;this.Ja()};_.y(ly,_.Rp);_.k=ly.prototype;_.k.O=function(){ly.J.O.call(this);this.D&&this.D.fa();this.K&&this.K.fa()};
_.k.vd=function(){ly.J.vd.call(this);var a=_.W("gb_Re",this.o);a&&_.Co(this,a,_.ql,(0,_.u)(this.Ng,this));(a=_.W("gb_Qe",this.o))&&_.Co(this,a,_.ql,(0,_.u)(this.hg,this));(a=_.W("gb_Se",this.o))&&_.Co(this,a,_.ql,(0,_.u)(this.Sg,this));(a=_.W("gb_zb",this.o))&&_.Co(this,a,_.ql,(0,_.u)(this.Bg,this))};_.k.Ja=function(){ly.J.Ja.call(this);this.B&&this.A(this.B,"focus",this.Vg,!1,this)};_.k.Ic=function(a){this.H.log(_.di(a.target,"gb_ab")?42:43);ly.J.Ic.call(this,a)};_.k.Vg=function(){my(this)};
_.k.Ng=function(){this.H.log(10)};_.k.hg=function(){this.H.log(48)};_.k.Sg=function(){this.H.log(9,{l:"o"})};_.k.Bg=function(){this.H.log(49)};_.k.$b=function(a,c){ly.J.$b.call(this,a,c);1==a&&ny(this)};_.k.open=function(a){ny(this);ly.J.open.call(this,a)};
var oy=function(a){if(!a.D){var c=_.W("multiLogin",a.o);c&&(a.D=new by(c,a.C,a.P,a.w,a.H))}return a.D},ny=function(a){if(!a.M){a.M=!0;var c=oy(a);if(c.W&&!c.D){_.eq(c.F,window,"message",(0,_.u)(c.Y,c));var d=_.eg(c.B);d.b.add("origin",hy());d=_.R("IFRAME",{width:0,height:0,frameborder:0,"class":"gb_7a",src:d.toString()});window.document.body.appendChild(d);c.D=!0}if(_.G(a.C,12)&&(c=_.W("gb_qb",a.o))&&window.location.host==window.top.location.host){var d=_.W("gb_9a",a.b),e=_.M(_.I(a.C,6,30)),f=_.W("gb_tb",
a.o),g=_.M(_.I(a.C,7,96));a.K=new Xx(d,e,f,g,a.w,a.H);_.Co(a,c,_.ql,a.N)}my(a)}};ly.prototype.N=function(a){var c=this.K;_.br(c.b,(0,_.u)(c.H,c,!0));a.preventDefault()};var my=function(a){if(a.o&&!a.o.hasAttribute("img-loaded")){for(var c=a.o.getElementsByTagName("img"),d=0,e;e=c[d];d++)e.hasAttribute("data-src")&&(e.setAttribute("src",e.getAttribute("data-src")),e.removeAttribute("data-src"));a.o.setAttribute("img-loaded","1")}};
ly.prototype.X=function(a,c,d,e,f,g,h,l,q,r){var v=oy(this);v.ca.log(44,{n:"paa"});r=r?2:1;a=fy(v,{Ya:f,id:"",Le:a,Me:c,Ne:d,zd:!1,Dd:g?h||"":"",name:e||"",$e:q||"",type:r});l&&(l["class"]&&(_.ti(a,l["class"].split(" ")),delete l["class"]),delete l.href,"_blank"==a.target&&delete l.target,_.Wc(a,l));g||_.V(a,"gb_Ib");gy(v,a,r)};ly.prototype.Y=function(){ey(oy(this))};ly.prototype.W=function(){for(var a=oy(this),c=0;c<a.o.length;c++)_.gh(a.o[c]);a.o=[];cy(a);dy(a,!1)};
var qy=function(a,c,d,e,f){var g=_.lh(window);this.G=a;this.H=c;this.D=d;this.K=e;this.o={};_.Qq.call(this,"onepick",ay(py(this)).toString(),f);_.Op(new _.Np(g),this.o)};_.y(qy,_.Qq);
var py=function(a){var c=a.K.join("-c,")+"-c",d=new Hx;d.b.type="ofuser";var e=new $x;_.dg(e.b,"profilePhoto","true");_.dg(e.b,"hostId","og");d=Zx(Rx(Rx(Rx(e,new jy("profile")),new Hx),d),"iframes");_.dg(d.b,"actions","loaded");_.dg(d.b,"thumbs",c);_.dg(d.b,"hl",a.G);_.dg(d.b,"authuser",a.H);a.D&&_.dg(d.b,"groupId",a.D);0<=_.xa(_.jf,"10.1")&&Rx(d,new iy("profile","photos"));return d};_.k=qy.prototype;_.k.md=function(){return{message:(0,_.u)(this.cc,this)}};
_.k.cc=function(a){this.ea.dispatchEvent(new _.Sq("message",[a]))};_.k.ld=function(){return{onOpen:(0,_.u)(this.Kg,this),onReady:(0,_.u)(this.Lg,this),onClose:(0,_.u)(this.Jg,this)}};_.k.$c=function(a){this.ea=a};_.k.Kg=function(a){this.b=a;this.o.onOpen&&this.o.onOpen(a)};_.k.Lg=function(){_.Rq(this,3)};_.k.Jg=function(a){this.o.onClose&&this.o.onClose(a)};
var ry=function(a,c,d,e,f){_.Rp.call(this,a,"aw",d,e,!0,f);this.C=ky(_.dq("gb_O",this.b),2,c,d,e);this.G=29;this.ha=30;this.ta=29;this.Fa=30;this.Ja()};_.y(ry,_.Rp);ry.prototype.O=function(){ry.J.O.call(this);for(var a=0;a<this.C.length;a++)this.C[a].fa();this.C=null};var sy=function(a,c,d,e){_.Ap.call(this,a,d);this.o=ky(_.dq("gb_P",this.b),1,c,d,e)};_.y(sy,_.Ap);sy.prototype.O=function(){sy.J.O.call(this);for(var a=0;a<this.o.length;a++)this.o[a].fa();this.o=null}; _.Wg(function(){var a=!!_.N().hd(),c=_.W("gb_fa"),d=_.W("gb_ia");if(a&&c&&d){var a=_.bc(),a=_.K(_.G(a,11)),d=_.Wl(),e=_.Yl(),f=_.Tg();new ry(c,a,d,e,f);(c=_.W("gb_sf"))&&new sy(c,a,d,e)}});
(function(){var a=_.J(_.N(),Ax,10)||new Ax,c=_.Rg(),d=_.Wl(),a=new qy(_.L(_.G(_.bc(),5)),_.L(_.G(c,5)),_.L(_.G(c,7)),[_.I(a,6,30),_.I(a,7,96)],d),d=new _.Zq(a,_.Do()||new _.no,d),a=_.og("gc");_.Ja("op",d.init(a));_.Wg(function(){var a=_.W("gb_mb"),c=_.W("gb_gb");a&&c&&a.parentNode!=c&&c.appendChild(a)})})();
_.Wg(function(){if(_.J(_.N(),Ax,10)){var a=_.W("gb_gb");if(a){var c=_.J(_.N(),Ax,10)||new Ax,d=_.Rg(),e=_.Wl(),f=_.Yl(),g=_.Tg(),a=new ly(a,c,d,e,f,g);_.x("gbar.spd",(0,_.u)(a.open,a));_.x("gbar.paa",(0,_.u)(a.X,a));_.x("gbar.pca",(0,_.u)(a.W,a));_.x("gbar.pcm",(0,_.u)(a.Y,a));_.og("api").Sa()}}});
_.Wg(function(){var a=_.eu();null==a.b&&a.init();_.bu(a,{});_.og("api").Sa();a.b.Ed()});var ty=function(a,c,d,e,f,g,h){_.rq.call(this,a,"gbd3",c,d,f,_.M(_.I(e,1,10)),"onShowShareboxOnly","onHoverSharebox",g,h,!0);this.G=3;this.Ia=!0;this.N=[];this.K="gb_Fe";this.P=_.L(_.G(e,3));this.Ja()};_.y(ty,_.rq);ty.prototype.open=function(){if(0<this.N.length){for(var a={},c=!1,d=(0,_.u)(this.ca,this),e=0,f;f=this.N[e];++e)try{var g=f(d);if(g){for(var h in g)a[h]=g[h];c=!0}}catch(l){this.w.log(l)}_.uq(this.D,"setPrefill",[a,!c])}ty.J.open.call(this)}; ty.prototype.ca=function(a){_.uq(this.D,"setPrefill",[a])};
window.location.host==window.top.location.host&&_.Wg(function(){var a=_.W("gb_Ee");if(a){var c=_.Wl(),d=_.Yl(),e=_.cp("gb"),f=_.og("if"),g=new ty(a,_.Do()||new _.no,f,_.J(_.N(),zx,8)||new zx,e,c,d);_.x("gbar.asmc",function(a){g.N.push(a)})}});
}catch(e){_._DumpException(e)}
})(this.gbar_);
// Google Inc.
