try{
var s_Xia,s_Yia,s_xi,s_Zia,s_yi,s__ia={};s_E("sy48");var s_zi=function(a){s_I(this,a,0,2,null,null)};s_h(s_zi,s_H);s_zi.prototype.jh=function(){return s_(this,1)};var s_0ia={};var s_Ai=s_d,s_Bi=s_Ia(0),s_Ci=s_Ia(0),s_Di=s_Ia(0),s_1ia=function(a,b){window.scrollBy(a,b)},s_Ei=function(a,b){window.scrollTo(a,b)},s_Fi=s_Ja,s_Gi=s_Ja,s_2ia=s_d,s_3ia=s_vb.match(/ GSA\/([.\d]+)/),s_Hi=s_3ia?s_3ia[1]:"";s_Zia=(s_yi=!!s_3ia)&&0<=s_lb(s_Hi,"4");s_xi=s_yi&&0<=s_lb(s_Hi,"5.2");s_Yia=s_yi&&0<=s_lb(s_Hi,"5.7");s_Xia=s_yi&&0<=s_lb(s_Hi,"4.3")&&0>s_lb(s_Hi,"4.5");

s_D("sy48");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy52");var s_Ii=function(){if(document.body){var a=s_6e(document.body).top;s_Ii=s_Ia(a);return a}return 0},s_4ia=s_d,s_5ia=s_d;
s_D("sy52");s_F();
}catch(e){_DumpException(e)}
try{
s_E("em3");
s_D("em3");s_F();
}catch(e){_DumpException(e)}
try{
s_E("em1");
s_D("em1");s_F();
}catch(e){_DumpException(e)}
try{
s_E("em2");
s_D("em2");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy54");var s_ej={vta:{},Kja:function(a,b,c){var d=c?1:0;if(!s_ha(0!=d?"velour.loadJsInterfaceWithFlags":"velour.loadJsInterface"))return s_Kd("No Velour.");a in s_ej.vta||(s_ej.vta[a]={});c=s_ej.vta[a];if(c[b])return c[b];var e=s_Md(),f=0!=d?window.velour.loadJsInterfaceWithFlags(a,b,d):window.velour.loadJsInterface(a,b),d="google.velourCb."+a+"."+b;s_sa(d,{onSuccess:function(){e.resolve(f.getResult())},onFailure:function(){e.reject(a+"."+b+" failed to load: "+f.getError().getMessage())}});f.setCallback(d);
return c[b]=e.$},call:function(a,b,c,d){for(var e=[a,b,!1],f=2;f<arguments.length;f++)e.push(arguments[f]);return s_ej.O3a.apply(s_ej,e)},O3a:function(a,b,c,d,e){for(var f=s_ej.Kja(a,b,c),g=[],k=4;k<arguments.length;k++)g.push(arguments[k]);return f.then(function(a){return a[d]?a[d].apply(a,g):s_Kd(d+" not found")})}};

s_D("sy54");s_F();
}catch(e){_DumpException(e)}
try{
s_E("em0");
s_D("em0");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy328");var s_95a=!1,s_$5a=null,s_b6a=function(){var a=s_a6a;s_we(window,"beforeunload",function(){s_95a||s_$5a.set("isn",a)})};if(s_yi){var s_$5a=s_Aj("session","isn"),s_a6a,s_c6a,s_d6a,s_e6a=s_Vg("isn").split(":");s_d6a=s_e6a[0];s_c6a=s_e6a[1];(s_a6a=s_d6a?s_5a(s_c6a,s_d6a):null)&&s_b6a()};

s_D("sy328");s_F();
}catch(e){_DumpException(e)}
try{
s_E("aa");
s_D("aa");s_F();
}catch(e){_DumpException(e)}
try{
s_E("abd");var s_Lx=function(a){for(var b="",c=21,d=0;d<a.length;d++)3!=d%4&&(b+=String.fromCharCode(a[d]^c),c++);return b},s_AZa=s_Lx([97,119,115,111,107]),s_BZa=s_Lx([120,116,82,108,118,125]),s_CZa=s_Lx([97,119,115,111,107,123]),s_DZa=s_Lx([118,115,121,107,108,124,104,119,68,127,114,105,114]),s_EZa=s_Lx([101,126,118,102,118,125,118,109,126]),s_FZa=s_Lx([116,116,115,108]),s_GZa=s_Lx([102,113,123,105]),s_HZa=s_Lx([102,116,99,108]),s_IZa=s_Lx([102,119,118,111]),s_JZa=s_Lx([113,119,118,111]),s_KZa=s_Lx([113,115,
99,107]),s_LZa=s_Lx([113,115,101,107]),s_MZa=s_Lx([113,115,117,107]),s_NZa=s_Lx([122,100,103,124,112,120,116,107,104]),s_OZa=s_Lx([58,127,122,103,121,126,127,98,104,51,109,124,118,123,15,76,70,68,79,95,10,66,79,97,65]),s_PZa=s_Lx([58,127,122,103,121,126,127,98,104,51,109,124,118,123,15,76,81,90,13,95,67,76,64,118]),s_QZa=function(){var a=s_q(s_AZa),b=s_q(s_BZa),c=s_q(s_CZa);return a||b||c?s_Ic()&&(a&&4E3<s_ff(a,s_NZa,!1)||b&&4E3<s_ff(b,s_NZa,!1)||c&&4E3<s_ff(c,s_NZa,!1))?1:0:0},s_RZa=function(a){var b=
0,c;for(c in a)if(a[c].e)if(a[c].b)b++;else return!1;return 0<b},s_SZa=function(a){a=a||{};var b={};b[s_KZa]={e:!!a[s_KZa],b:!s_vj(s_AZa)};b[s_LZa]={e:!!a[s_LZa],b:!s_vj(s_BZa)};b[s_MZa]={e:!!a[s_MZa],b:!s_vj(s_CZa)};return b},s_TZa=function(a){var b=[],c;for(c in a)a[c].e&&b.push(c+":"+(a[c].b?"1":"0"));return b.join(",")},s_UZa=function(a,b){a=String(a);b&&(a+=","+b);google.log(s_EZa,a)},s_VZa=function(a,b,c){c=null!=c?c:2;if(1>c)s_UZa(7,b);else{var d=new Image;d.onerror=s_f(s_VZa,a,b,c-1);d.src=
a}};s_wf("abd",{init:function(a){a=a||{};if(a[s_FZa]&&s_vj(s_DZa)){var b=s_SZa(a),c=s_TZa(b);s_RZa(b)?(b=a[s_HZa]?0:s_QZa(),s_UZa(1,String(b)+","+c)):s_UZa(0,c);a[s_GZa]||s_VZa(s_OZa,"gfl");a[s_IZa]||(a[s_JZa]?s_Tf(function(){s_VZa(s_PZa,"aa")}):s_VZa(s_PZa,"aa"))}}});

s_D("abd");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy78");
s_D("sy78");s_F();
}catch(e){_DumpException(e)}
try{
var s_Bma=function(a){return a.ka||(a.ka=a.ha())},s_Cma=function(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};s_E("sy77");var s_ek=function(a){s_Ge.call(this);this.headers=new s_td;this.Bna=a||null;this.eq=!1;this.yna=this.Te=null;this.C_="";this.UN=0;this.aU="";this.DT=this.$xa=this.oja=this.ata=!1;this.E$=0;this.my=null;this.eV="";this.zEa=this.YB=!1};s_h(s_ek,s_Ge);s_ek.prototype.Bd=null;var s_Dma=/^https?$/i,s_Ema=["POST","PUT"],s_Fma=[],s_fk=function(a,b,c,d,e,f,g){var k=new s_ek;s_Fma.push(k);b&&k.listen("complete",b);k.hn("ready",k.FYa);f&&k.EV(f);g&&(k.YB=g);k.send(a,c,d,e);return k};
s_ek.prototype.FYa=function(){this.dispose();s_Nb(s_Fma,this)};s_ek.prototype.EV=function(a){this.E$=Math.max(0,a)};s_ek.prototype.kP=function(a){this.eV=a};
s_ek.prototype.send=function(a,b,c,d){if(this.Te)throw Error("p`"+this.C_+"`"+a);b=b?b.toUpperCase():"GET";this.C_=a;this.aU="";this.UN=0;this.ata=!1;this.eq=!0;this.Te=this.lqa();this.yna=this.Bna?s_Bma(this.Bna):s_Bma(s_nea);this.Te.onreadystatechange=s_e(this.qNa,this);try{this.$xa=!0,this.Te.open(b,String(a),!0),this.$xa=!1}catch(f){this.Ni(5,f);return}a=c||"";var e=this.headers.clone();d&&s_Eba(d,function(a,b){e.set(b,a)});d=s_Hb(e.Pf(),s_Gma);c=s_ga.FormData&&a instanceof s_ga.FormData;!s_Ib(s_Ema,
b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.Te.setRequestHeader(b,a)},this);this.eV&&(this.Te.responseType=this.eV);"withCredentials"in this.Te&&this.Te.withCredentials!==this.YB&&(this.Te.withCredentials=this.YB);try{s_Hma(this),0<this.E$&&((this.zEa=s_Ima(this.Te))?(this.Te.timeout=this.E$,this.Te.ontimeout=s_e(this.Ij,this)):this.my=s_3h(this.Ij,this.E$,this)),this.oja=!0,this.Te.send(a),this.oja=!1}catch(f){this.Ni(5,f)}};
var s_Ima=function(a){return s_3c&&s_dd(9)&&s_oa(a.timeout)&&s_c(a.ontimeout)},s_Gma=function(a){return s_iha("Content-Type",a)};s_ek.prototype.lqa=function(){return this.Bna?this.Bna.$():s_Of()};s_ek.prototype.Ij=function(){"undefined"!=typeof s_haa&&this.Te&&(this.aU="Timed out after "+this.E$+"ms, aborting",this.UN=8,this.dispatchEvent("timeout"),this.abort(8))};s_ek.prototype.Ni=function(a,b){this.eq=!1;this.Te&&(this.DT=!0,this.Te.abort(),this.DT=!1);this.aU=b;this.UN=a;s_Jma(this);s_Kma(this)};
var s_Jma=function(a){a.ata||(a.ata=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};s_ek.prototype.abort=function(a){this.Te&&this.eq&&(this.eq=!1,this.DT=!0,this.Te.abort(),this.DT=!1,this.UN=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),s_Kma(this))};s_ek.prototype.Ha=function(){this.Te&&(this.eq&&(this.eq=!1,this.DT=!0,this.Te.abort(),this.DT=!1),s_Kma(this,!0));s_ek.Ba.Ha.call(this)};
s_ek.prototype.qNa=function(){this.isDisposed()||(this.$xa||this.oja||this.DT?s_Lma(this):this.hkb())};s_ek.prototype.hkb=function(){s_Lma(this)};
var s_Lma=function(a){if(a.eq&&"undefined"!=typeof s_haa&&(!a.yna[1]||4!=a.QK()||2!=a.getStatus()))if(a.oja&&4==a.QK())s_3h(a.qNa,0,a);else if(a.dispatchEvent("readystatechange"),4==a.QK()){a.eq=!1;try{a.isSuccess()?(a.dispatchEvent("complete"),a.dispatchEvent("success")):(a.UN=6,a.aU=a.owa()+" ["+a.getStatus()+"]",s_Jma(a))}finally{s_Kma(a)}}},s_Kma=function(a,b){if(a.Te){s_Hma(a);var c=a.Te,d=a.yna[0]?s_d:null;a.Te=null;a.yna=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},
s_Hma=function(a){a.Te&&a.zEa&&(a.Te.ontimeout=null);s_oa(a.my)&&(s_4h(a.my),a.my=null)};s_a=s_ek.prototype;s_a.dd=function(){return!!this.Te};s_a.isSuccess=function(){var a=this.getStatus(),b;if(!(b=s_Cma(a))){if(a=0===a)a=s_bc(1,String(this.C_)),!a&&s_ga.self&&s_ga.self.location&&(a=s_ga.self.location.protocol,a=a.substr(0,a.length-1)),a=!s_Dma.test(a?a.toLowerCase():"");b=a}return b};s_a.QK=function(){return this.Te?this.Te.readyState:0};
s_a.getStatus=function(){try{return 2<this.QK()?this.Te.status:-1}catch(a){return-1}};s_a.owa=function(){try{return 2<this.QK()?this.Te.statusText:""}catch(a){return""}};s_a.Hm=function(){try{return this.Te?this.Te.responseText:""}catch(a){return""}};var s_gk=function(a,b){if(a.Te)return a=a.Te.responseText,b&&0==a.indexOf(b)&&(a=a.substring(b.length)),s_Aa(a)};
s_ek.prototype.lA=function(){try{if(!this.Te)return null;if("response"in this.Te)return this.Te.response;switch(this.eV){case "":case "text":return this.Te.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.Te)return this.Te.mozResponseArrayBuffer}return null}catch(a){return null}};s_ek.prototype.getResponseHeader=function(a){if(this.Te&&4==this.QK())return a=this.Te.getResponseHeader(a),null===a?void 0:a}; s_ek.prototype.getAllResponseHeaders=function(){return this.Te&&4==this.QK()?this.Te.getAllResponseHeaders():""};var s_hk=function(a){return s_na(a.aU)?a.aU:String(a.aU)};

s_D("sy77");s_F();
}catch(e){_DumpException(e)}
try{
var s_ik=function(a){for(var b in a)return a[b]};s_E("sy76");var s_Mma=function(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"."+a[b]}).join(",")},s_Nma=function(a){var b=Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&");b&&(b="&"+b);return b},s_Oma=function(a){a=s_Mma(a);var b={};return b.rt=a,b};
var s_jk=function(){this.ka=this.$=0},s_Pma=function(){var a=window.performance;return a&&a.now?a.now():s_g()};s_jk.prototype.start=function(){this.$=this.$||s_Pma()};s_jk.prototype.pause=function(){this.ka=this.$?this.ka+s_Pma()-this.$:this.ka;this.$=0};var s_lk=function(){var a=s_kk;return Math.round(a.ka+(a.$?s_Pma()-a.$:0))};s_jk.prototype.reset=function(){this.ka=this.$=0};
var s_Qma=function(a){function b(a,b){c.push(encodeURIComponent(b)+":"+encodeURIComponent(a))}var c=[];a instanceof Map?a.forEach(b):s_Qa(a,b);return c.join(",")};var s_Rma="authuser deb e esrch expflags expid fesp gl hl host hotel_dates hotel_ds noj ogdeb opti opts optq optt mergelabel mlp plugin rlst skew_host source_ip ssl_dbg st tbcp tbs tcfs useragent uuld uule v".split(" "),s_Sma=function(){return""},s_Vma=function(a,b,c,d,e,f,g,k,l){b=s_Tma(b,d,e,f,g,k);l&&(b.q=encodeURIComponent(l));s_4a(b,c);return s_Sma(b)+"/async/"+a+s_Uma(b)},s_Wma=function(a,b,c,d,e,f,g,k){var l="/search",m=b.q,n=b.start;delete b.q;delete b.start;b=s_Tma(b,d,e,f,g,!1);void 0!=
m&&(b.q=encodeURIComponent(m));void 0!=n&&(b.start=n);k&&(b.sns="1",l="/s");b.asearch=a;s_4a(b,c);return l+s_Uma(b)},s_Tma=function(a,b,c,d,e,f){var g={};f&&(g.dfsl=1);(a=s_Qma(a))&&(g.async=a);b&&(a=new s_$e,s_vg(a,b),(b=s_df(a))&&(g.vet=s_fc(b,"vet")));d?(g.ved=d,c&&(g.ei=c)):g.ei=c?c:google.kEI;null!=e&&(g.lei=e);s_j(s_Rma,function(a){var b=s_Vg(a);b&&(g[a]=encodeURIComponent(b))});c=s_Xg(new s_cg);s_4a(g,s_qg(c));g.yv=2;return g},s_Uma=function(a){if(s_Za(a))return"";var b=[];s_Qa(a,function(a, d){b.push(d+"="+a)});return"?"+b.join("&")};
var s_Xma=!1,s_kk=new s_jk,s_Yma=new function(){var a={};this.$=void 0===a.path?"gen_204":a.path},s_mk=function(a,b,c,d,e,f,g,k,l,m){l=void 0===l?{}:l;s_kk=new s_jk;s_kk.start();b._fmt=c;var n=s_Zma(a);a=s_Vma(a,b,l,d,m,e,k,g,f);n.rt.ub=s_lk();return s__ma(a,c,n)},s_0ma=function(a,b,c,d,e,f,g,k){b._fmt="jspb";b.q=c;s_kk=new s_jk;s_kk.start();c=s_Zma(a);a=s_Wma(a,b,d||{},e,void 0,f,g,k);c.rt.ub=s_lk();return s__ma(a,"jspb",c)},s__ma=function(a,b,c){var d=s_Md();c.rt.fr=s_lk();s_fk(a,function(a){var e=
a.target,g=e.Hm();c.rt.bs=g.length;if("complete"==a.type&&e.isSuccess())if(c.rt.st=s_lk(),s_1ma(c),s_9a(g,")]}'\n")&&(g=g.substr(5)),"json"==b){var k;try{JSON?k=JSON.parse(g):k=s_Ba(g)}catch(l){d.reject(l)}s_qa(k)&&(k=s_ik(k),a=k.__err__,s_c(a)&&d.reject(a));d.resolve(k)}else d.resolve(g);else c.rt.ft=s_lk(),s_1ma(c),d.reject(void 0)},void 0,void 0,void 0,void 0,!1);return d.$},s_1ma=function(a){if(s_c(window.navigator.sendBeacon)&&s_Xma){a=Object.assign(a,s_Oma(a.rt));a=Object.assign({},a);var b= "";s_c(a.ct)&&(b=a.ct,delete a.ct);a=s_Nma(a);a=google.logUrl(b,a,void 0,void 0,s_Yma.$);null!=window.navigator.sendBeacon&&navigator.sendBeacon(a)}},s_Zma=function(a){var b={};b.astyp=a;b.rt={};return b};

s_D("sy76");s_F();
}catch(e){_DumpException(e)}
try{
var s_2ma=function(a,b){return s_Db(b,function(a,b){return a.Ef(b)},a)},s_3ma=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);s_ae(a)}},s_4ma=function(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1},s_5ma=function(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return s_4ma(b,a)},s_6ma=function(a){if(!a)return{};var b={};s_j(a.split(","),function(c){c=c.split(":");2!=c.length&&
google.ml(Error("T"),!1,{_sn:"as_badCtx",cxt:a});b[decodeURIComponent(c[0])]=decodeURIComponent(c[1])});return b},s_7ma=function(){var a=s_wg(),a=s_Lj(a);if(!a.q){var b=s_Lj(s_Ff());b.q&&(a.q=b.q,s_ic().hash=s_hka(a))}},s_8ma=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(s_3c&&!s_ed(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;
if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?s_4ma(a,b):!c&&s_ie(e,b)?-1*s_5ma(a,b):!d&&s_ie(f,a)?s_5ma(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=s_Sd(a);c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(s_ga.Range.START_TO_END,a)},s_9ma=function(a,b){for(var c=a.search(s_fba),d=0,e,f=[];0<=(e=s_eba(a,d,b,c));){d=a.indexOf("&",e);if(0>d||d>c)d=c;e+= b.length+1;f.push(s_eb(a.substr(e,d-e)))}return f},s_$ma=function(a,b){var c={};s_j(a,function(d,e){c[b.call(void 0,d,e,a)]=d});return c},s_ana=function(a){a>s_wa?s_xa=1:a<s_wa&&(s_xa=2)};s_E("sy79");
var s_bna=!1,s_nk={preload:"yp",filled:"yf",inlined:"yi"},s_cna=s_3a(s_nk),s_dna={loading:"yl",error:"ye"},s_ena=s_3a(s_dna),s_fna={preload:"asyncReset",filled:"asyncFilled",loading:"asyncLoading",error:"asyncError"},s_gna=function(){};s_h(s_gna,Error);var s_ok=function(a){this.element=a;this.type=s_o(a,"asyncType")||"";if(!this.type)throw a=new s_gna,s_va(a),a;},s_pk=function(a){var b=s_o(a,"asyncTrigger");if(b){if(a=s_q(b))return new s_ok(a);a=new s_gna;s_va(a);throw a;}return new s_ok(a)};
s_ok.prototype.getState=function(){var a=s_rc(this.element);return s_Hb(s_Cb(a,function(a){return s_cna[a]}),s_Ma)};var s_hna=function(a){a=s_rc(a.element);return s_Hb(s_Cb(a,function(a){return s_ena[a]}),s_Ma)||""};s_ok.prototype.setState=function(a){s_ina(this,a);"filled"==a&&s_j(this.element.querySelectorAll("."+s_nk.inlined),function(a){s_ina(new s_ok(a),"filled")})};
var s_qk=function(a,b){s_tc(a.element,s_Va(s_dna));if(""!=b){s_l(a.element,s_dna[b]);var c=a.getState();s_Qh(a.element,s_fna[b],{state:c,Z7:b})}},s_ina=function(a,b){s_tc(a.element,s_Va(s_nk));s_l(a.element,s_nk[b]);s_qk(a,"");s_Qh(a.element,s_fna[b],{state:b,Z7:""})},s_jna=function(a){return(a=s_o(a.element,"asyncContextRequired"))?a.split(","):[]},s_rk=function(a,b,c,d){this.target=a;this.trigger=c;c=b=s_2a(b);var e;var f=this.trigger||this.target.element;e=s_jna(this.target);var g=b;if(e.length){e=
new s_Qd(e);for(var g=new s_Qd(s_Wa(g)),k={};f&&null!=f.parentNode&&!s_Wca(e,g);){var l=s_o(f,"asyncContext");if(l)for(var l=l.split(";"),m=0;m<l.length;++m){var n=l[m].split(":");2==n.length?(n[0]=s_eb(n[0]),n[1]=s_eb(n[1]),e.contains(n[0])&&!g.contains(n[0])&&(k[n[0]]=n[1],g.add(n[0]))):s_va(Error("W"),{cxt:l[m]})}f=f.parentNode}e=k}else e={};s_4a(c,e);c=b;e=this.target.element;e.id!=this.target.type&&(c._id=e.id);(e=s_o(this.target.element,"asyncToken"))&&(c._xsrf=e);c._pms=s_xb(google.xjsu,"k").match(/xjs\.(\w+)\./)[1];
this.context=b;this.$=d||{};this.Mr="stateful"==s_o(a.element,"asyncMethod")||s_o(a.element,"asyncToken")?"POST":"GET";this.ka=s_o(a.element,"asyncRclass")||""},s_sk=function(a,b,c,d){if(s_ge(a))e=s_pk(a),a=s_o(a,"asyncTrigger")?a:void 0;else{var e=a;a=c}return new s_rk(e,b||{},a,d)},s_kna=function(a,b,c){var d;d=b.getStatus()?Error("vd"):Error("wd");d.details={s:b.getStatus()};c&&(d.details.e=c);0==b.getStatus()&&s_va(d,d.details);a.reject(d)},s_lna=function(a){var b="POST"==a.Mr?{}:a.context,c=
s_Fe(a.target.element),d=google.getEI(a.target.element),e=a.trigger?s_Fe(a.trigger):void 0,f=a.trigger?google.getLEI(a.trigger):void 0;return("search"==a.ka?s_Wma:s_Vma)(a.target.type,b,a.$,c,d,e,f)},s_mna=function(a){if("POST"==a.Mr){var b={},c=s_Qma(a.context);c&&(b.async=a.target.type+","+c);var d=[];s_Qa(b,function(a,b){d.push(b+"="+a)});return d.join("&")}};
s_rk.prototype.fetch=function(){var a;a=new s_Qd(s_jna(this.target));var b={};s_4a(b,this.context);s_4a(b,this.$);b=new s_Qd(s_Wa(b));s_Wca(a,b)?a=!0:(a=s_Vca(a,b).Xc().join(","),s_va(Error("U"),{type:this.target.type,cxt:a}),a=!1);return a?s_nna(this):s_Kd(void 0)};
var s_nna=function(a){var b=s_Md(),c=s_lna(a),c=c+(s_qaa&&s_ya?s_za():""),d=a.target.type;s_fk(c,function(a){var c=a.target;if("complete"==a.type)if(c.isSuccess()){a=c.Hm();var e="\n\n";s_gb(a,e)||(e="\n");a=s_Bb(a.split(e),s_Ma);var k=[];a=s_Bb(s_Cb(a,function(a){try{var d=JSON.parse(a),e=d.__err__;if(s_c(e))s_kna(b,c,e);else return s_pka(d)}catch(ba){s_Vg("deb")?k.push(ba):(s_kna(b,c),s_va(ba,{a:"1"}))}}),s_Ma);(e=c.getResponseHeader("Version"))&&s_ana(parseInt(e,10));b.resolve(a)}else s_kna(b,
c);else s_kna(b,c),s_va(Error("V"),{type:d})},a.Mr,s_mna(a),void 0,void 0,s_bna);return b.$},s_ona=function(){s_j(document.querySelectorAll("."+s_nk.inlined),function(a){s_ina(new s_ok(a),"filled")})},s_uk=function(a){var b=s_pk(a);return"preload"!=b.getState()||"loading"==s_hna(b)?s_p(void 0):s_tk(a,void 0,void 0,void 0)},s_tk=function(a,b,c,d,e){if(b instanceof Map){var f=b;b={};f.forEach(function(a,c){b[c]=a})}var g=e?s_sk(s_pk(a),b,e):s_sk(a,b);a=c||1;1!=a&&(d=d?d(g.context):g.context,s_pna(g.target.element.id,
g.target.type,d,a));s_qk(g.target,"loading");return s_Od(g.fetch().then(function(a){s_j(a,function(a){a.apply()});g.target.setState("filled")}),function(a){s_qk(g.target,"error");throw a;})},s_qna=function(a){var b={};a.forEach(function(a,d){b[d]=a});return b},s_vk=function(a,b,c){var d;void 0!=c&&(d=s_qna(c));var e=s_sk(a,b,void 0,d);s_qk(e.target,"loading");return s_Od(e.fetch().then(function(a){s_j(a,function(a){(new s_Oj(a.Pl,s_Rj.Et())).append(a)});e.target.setState("filled")}),function(a){s_qk(e.target,
"error");throw a;})},s_wk=function(a,b,c){return s_sk(a,b,c,void 0).fetch()},s_yk=function(a){a=s_sk(a);delete s_xk[a.target.element.id];s_Pg("async",s_rna(),!1);s_7d(a.target.element);s_Dha(a.target.element.id);a.target.setState("preload")},s_sna=function(a,b,c){this.id=a;this.type=b;this.context=c},s_tna=function(a){if(!a)return null;var b=s_rb(a,",",1);a=b[0];var b=s_6ma(b[1]),c=b._id||a;s__a(b,"_id");return new s_sna(c,a,b)};
s_sna.prototype.yb=function(){var a=s_2a(this.context);this.id!=this.type&&(a._id=this.id);return s_Za(a)?this.type:this.type+","+s_Qma(a)};s_sna.prototype.apply=function(){var a=document.getElementById(this.id);if(!a)return!1;if(s_o(a,"asyncDisableReplay"))return!0;s_tk(a,this.context);return!0};
var s_una=function(a){a=s_Cb(a.split(";"),s_tna);a=s_Bb(a,function(a){return null!=a});return s_$ma(a,function(a){return a.id})},s_rna=function(){var a=s_Cb(s_Va(s_xk),function(a){return a.yb()});return s_Bb(a,function(a){return null!=a}).join(";")},s_xk={},s_vna="",s_pna=function(a,b,c,d){1!=d&&(c=s_Ra(c,function(a,b){return"_id"!=b}),s_xk[a]=new s_sna(a,b,c),a=s_rna(),a!=s_vna&&(s_Pg("async",a,3==d),s_Gj&&s_7ma()))},s_wna=function(a,b){s_vna=a;if(b)s_xk=s_una(a),s_Bb(s_Va(s_xk),function(a){return!a.apply()});
else{a=s_una(a);for(var c in s_xk)if(!(c in a)){var d=document.getElementById(c);d&&s_yk(d)}for(c in a)b=a[c],d=s_xk[c],d&&s_bg(d.context,b.context)||(d=document.getElementById(c))&&s_tk(d,b.context)}};s_xf("async",{init:function(a){a.slm&&(s_Xma=a.slm);s_Lg("async",s_wna);s_Zh("async",{u:function(a){s_tk(a)},uo:function(a){s_uk(a)},r:s_yk});s_ona()}});

s_D("sy79");s_F();
}catch(e){_DumpException(e)}
try{
s_E("em16");
s_D("em16");s_F();
}catch(e){_DumpException(e)}
try{
s_E("async");
s_D("async");s_F();
}catch(e){_DumpException(e)}
try{
s_E("erh");var s_osb=function(){var a="/webhp?ssrp=1",b=s_Wg("hl");b&&(a+="&hl="+b);s_Cf(a)};s_wf("erh",{init:function(){s_Zh("erh",{hc:s_osb})}});
s_D("erh");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy81");var s_zk=null,s_yna=!0,s_Ak=s_d;
s_D("sy81");s_F();
}catch(e){_DumpException(e)}
try{
var s_zna=function(){var a=s_q("fbar"),b=s_q("fuser")||s_q("fsr"),c=s_q("fsl");a&&b&&c&&(a=s_t("fbar",a),s_m(a,"fmulti"),32>a.clientWidth-c.offsetWidth-b.offsetWidth-30-34&&s_l(a,"fmulti"))},s_Ana=!1,s_Bna=!1,s_Cna=0,s_Dna=function(){var a=s_zk=s_zk||s_q("fbarcnt"),b=s_q("fbar");if(b&&a&&s_0e(a)&&(s_Ana||!s_Bna||s_Cna!=window.innerWidth)){s_Cna=window.innerWidth;s_x(a,{height:"auto"});s_x(b,{bottom:"",position:""});s_zna();if(s_q("dbg_"))s_x(b,{position:"static"});else{var c=window.innerHeight||Math.max(document.documentElement.clientHeight, document.body.scrollHeight),d=s_Pe(a).y,c=c-d;c>b.offsetHeight&&(s_x(a,{height:c+"px"}),s_x(b,{bottom:"0",position:"absolute"}))}s_x(a,{visibility:"visible"})}};s_E("foot");
var s_Ena=null,s_Bk=null,s_Ck=null,s_Gna=function(){if(s_0e(s_Bk))s_Ck.setAttribute("aria-expanded","false"),s_Fna();else{s_Ck.setAttribute("aria-expanded","true");var a=s_y(s_Bk),b=-20;if(s_ef())c=s_y(s_Ck),0>s_Pe(s_Ck).x+c.width-a.width-b&&(b=s_8e(s_Ck),b=c.width-a.width+b.left+b.right),s_Bk.style.right=b+"px";else{if(s_Pe(s_Ck).x+a.width+b>s_Zd().width)var c=s_y(s_Ck),b=s_8e(s_Ck),b=c.width-a.width+b.left+b.right;s_Bk.style.left=b+"px"}s_z(s_Bk,!0);s_ta(document.body,"click",s_Fna)}},s_Fna=function(a){a&&
a.target==s_Ck||s_z(s_Bk,!1);s_ua(document.body,"click",s_Fna)},s_Hna=function(a){s_Ena&&s_z(s_Ena,!a)};
s_wf("foot",{init:function(a){s_Bk=s_q("fsett");s_Ck=s_q("fsettl");s_Bk&&s_Ck&&s_Zh("foot",{cst:s_Gna});var b=s_q("fbar");b&&s_z(b,!0);s_Ena=s_q("footcnt");s_Hna(!1);var b=a.po,c=a.qe,d=a.pf;s_zk=s_q("fbarcnt");s_Ana=!!c;s_yna=null!=s_zk&&(void 0===d||d);s_Bna=!!b;s_Ak=s_yna?s_tf(null,s_Dna,!1):s_zna;s_Ak();s_ta(window,"resize",s_Ak);s_pf(165,s_Ak);void 0!==a.dv&&""!==a.dv&&s_2f.set("DV",a.dv,600)},dispose:function(){s_0h("foot",["cst"])}});s_pf(37,s_Hna);s_pf(155,s_f(s_Hna,!0));

s_D("foot");s_F();
}catch(e){_DumpException(e)}
try{
s_E("fpe");var s__Od,s_0Od=!1,s_p5=function(a){s_i.call(this);var b=a||!1;a=!!(s_Hj()&&window.gbar&&gbar.elc&&gbar.elr);this.qa=b&&!a;this.ma=[];s_0Od||(a&&gbar.elc(s_e(function(){b&&s_1Od(gbar.elr().mo);s_A(71)},this)),s_0Od=!0);this.qa&&(this.$=s_tf(null,s_e(this.Ea,this),!0),s_w(window,"resize",this.$,!1,this),this.$());(a=s_q("tbbcc"))&&this.ma.push(a);this.ha();s_w(window,"scroll",this.ha,!1,this)};s_h(s_p5,s_i);
s_p5.prototype.Ha=function(){this.ma=[];this.qa&&s_xe(window,"resize",this.$,!1,this);s_xe(window,"scroll",this.ha,!1,this)};var s_1Od=function(a){var b=s_q("cnt"),c=s_q("searchform");b&&(s_n(b,"big","lg"==a),s_n(b,"mdm","md"==a));c&&(s_n(c,"big","lg"==a),s_n(c,"mdm","md"==a))};s_p5.prototype.Ea=function(){s_1Od(1250<=document.body.offsetWidth?"lg":"sm")};s_p5.prototype.$=null;
s_p5.prototype.ha=function(){var a=window.pageXOffset||document.body.scrollLeft||document.documentElement.scrollLeft,b=s_ef(),c=b?"marginRight":"marginLeft",d=b?"right":"left";b&&(a=Math.abs(a));for(var b=0,e;e=this.ma[b];b++)"fixed"==s_Le(e)&&("tbbcc"==e.id?e.style[c]=-a+"px":e.style[d]=-a+"px")};s_wf("fpe",{init:function(a){s__Od=new s_p5(a.js)},dispose:function(){s__Od&&(s__Od.dispose(),s__Od=null)}});

s_D("fpe");s_F();
}catch(e){_DumpException(e)}
try{
s_E("ifl");var s_0O,s_1O,s_2O,s_3O,s_4O,s_40b,s_5O=!1,s_50b=-1,s_60b=null,s_70b=null,s_80b=!1,s_a1b=function(a){s_80b=a=s_90b(s_rf(a));var b=s_5O&&!a;!s_5O&&a?s_$0b(function(){s_80b&&(s_5O=!0,s_60b())},300):b&&s_$0b(function(){s_80b||(s_5O=!1,s_70b())},200)},s_$0b=function(a,b){window.clearTimeout(s_50b);s_50b=window.setTimeout(a,b)},s_90b=function(a){for(var b=0,c;c=s_40b[b];b++)if(a==c||s_ie(c,a))return!0;return!1};
var s_6O=0,s_b1b="",s_c1b=0,s_d1b=!1,s_e1b=function(){var a=s_1O.offsetWidth-s_c1b;return 0<=a?a:0},s_h1b=function(){if(s_0O){var a=s_1O.offsetLeft,b=s_1O.offsetTop;null===s_2O||s_mf(s_2O,"display","block","height",Math.max(s_1O.clientHeight,27)+"px","position","absolute","left",a+"px","margin","0","top",b+"px","width",s_e1b()+"px");s_mf(s_1O,"visibility","hidden");var c=s_3O?s_3O.getElementsByTagName("span"):[],a=c[s_6O]?-c[s_6O].offsetTop:s_3O.offsetTop;s_6O+=2+Math.floor(Math.random()*(s_0O.opts.length-
3));s_6O>=s_0O.opts.length&&(s_6O-=s_0O.opts.length);var b=s_6O,d=c[b],c=-d.parentNode.offsetTop;s_d1b&&(c+=3);s_2O.setAttribute("aria-label",d.innerHTML);var e=s_e1b(),d=Math.max(d.offsetWidth,e);s_4O&&s_4O.finish&&s_4O.finish();s_4O=s_zf(300,[[s_2O,"width",e,d],[s_3O,"top",a,c]]);s_ta(s_2O,"click",s_f1b);s_ta(window,"resize",s_7O);s_ta(window,"scroll",s_7O);s_ta(s_2O,"blur",s_7O);s_ta(s_2O,"keydown",s_g1b);google.log("ifl","1:"+s_0O.opts[b].id+"&ei="+google.getEI(s_2O)+"&ved="+s_b1b)}},s_7O=function(){if(s_2O&&
s_1O){var a=s_ff(s_2O,"width");s_4O&&s_4O.finish&&s_4O.finish();s_4O=s_zf(100,[[s_2O,"width",a,s_e1b()]],function(){null===s_1O||s_mf(s_1O,"visibility","inherit");null===s_2O||s_mf(s_2O,"display","none","width",s_e1b()+"px")});s_5O=!1;s_2O.setAttribute("aria-label","");s_2O.setAttribute("tabIndex","-1");s_ua(s_2O,"click",s_f1b);s_ua(window,"resize",s_7O);s_ua(window,"scroll",s_7O);s_ua(s_2O,"blur",s_7O);s_ua(s_2O,"keydown",s_g1b)}},s_f1b=function(a){var b;s_0O.opts[s_6O]?(b=s_0O.opts[s_6O],b=b.href+
"&ct=ifl&cad=2:"+b.id+"&ei="+google.getEI(s_2O)+"&ved="+s_b1b+"&rct=j"):b="";b&&(a.preventDefault&&a.preventDefault(),s_sf(a),google.nav.go(b))},s_i1b=function(){document&&document.activeElement!=s_2O&&(s_2O.setAttribute("tabIndex","0"),s_5O=!0,s_h1b(),s_2O.focus())},s_g1b=function(a){a=a||window.event;13!=a.keyCode&&32!=a.keyCode||s_f1b(a)};
s_wf("ifl",{init:function(a){s_1O=s_q("gbqfbb");if(a&&a.opts&&!s_0O&&s_1O){s_0O=a;s_d1b=a.lsf_is_launched;a=s_q("iflved");null===a||(s_b1b=s_o(a,"ved")||"");if(s_0O&&!s_2O){a=["<div>"];for(var b=0,c;c=s_0O.opts[b];b++)a.push("<div><span>"),a.push(c.msg),a.push("</span></div>");a.push("</div>");s_2O=s_lf("div.gbqfba gbqfba-hvr",a.join(""));s_2O.setAttribute("role","button");s_3O=s_2O.firstChild;s_9d(s_2O,s_1O);a=s_ff(s_1O.firstChild||s_1O,"font-family",!0);s_6O=Math.floor(Math.random()*s_0O.opts.length);
s_mf(s_2O,"display","none","fontFamily",a,"overflow","hidden","textAlign","center","zIndex","50");null===s_3O||s_mf(s_3O,"left","0","position","absolute","right","0","whiteSpace","nowrap")}s_c1b=2*s_ff(s_2O,"padding-left");a=s_7O;s_40b=[s_1O,s_2O];s_60b=s_h1b;s_70b=a;s_ta(document,"mouseover",s_a1b);s_ta(s_1O,"focus",s_i1b)}},dispose:function(){s_7O();s_4O&&s_4O.finish&&s_4O.finish();s_1O&&s_ua(s_1O,"focus",s_i1b);s_40b=null;s_5O=!1;s_70b=s_60b=null;s_80b=!1;s_ua(document,"mouseover",s_a1b);window.clearTimeout(s_50b); s_50b=-1;s_0O=s_1O=null;s_ae(s_2O);s_3O=s_2O=null;s_6O=0}});

s_D("ifl");s_F();
}catch(e){_DumpException(e)}
try{
s_E("ipv6");var s_Dk=null,s_Ina=function(a){s_sa("google.v6t",s_g());s_sa("google.v6s",0);s_Dk=new Image;s_sa("google.v6",s_Dk);s_Dk.onload=s_Dk.onerror=function(){s_sa("google.v6s",1)};s_Dk.src=a+"&rndm="+Math.random()};s_xf("ipv6",{init:function(a){a.url&&s_Ina(a.url)},dispose:function(){s_Dk=null}});

s_D("ipv6");s_F();
}catch(e){_DumpException(e)}
try{
var s_Fua=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?s_eb(f):"")}}},s_Gua=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^s_g()).toString(36)};s_E("sy153");
var s_0o=function(a,b){this.ka=this.Da=this.qa="";this.Ea=null;this.Wa=this.ma="";this.Ca=!1;var c;a instanceof s_0o?(this.Ca=s_c(b)?b:a.Ca,s_1o(this,a.qa),this.Da=a.Da,s_2o(this,a.ka),s_3o(this,a.Ea),s_4o(this,a.ma),s_5o(this,a.ha.clone()),s_6o(this,a.Wa)):a&&(c=String(a).match(s_$b))?(this.Ca=!!b,s_1o(this,c[1]||"",!0),this.Da=s_7o(c[2]||""),s_2o(this,c[3]||"",!0),s_3o(this,c[4]),s_4o(this,c[5]||"",!0),s_5o(this,c[6]||"",!0),s_6o(this,c[7]||"",!0)):(this.Ca=!!b,this.ha=new s_8o(null,0,this.Ca))};
s_0o.prototype.toString=function(){var a=[],b=this.qa;b&&a.push(s_9o(b,s_Hua,!0),":");var c=this.ka;if(c||"file"==b)a.push("//"),(b=this.Da)&&a.push(s_9o(b,s_Hua,!0),"@"),a.push(s_db(c).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Ea,null!=c&&a.push(":",String(c));if(c=this.ma)this.ka&&"/"!=c.charAt(0)&&a.push("/"),a.push(s_9o(c,"/"==c.charAt(0)?s_Iua:s_Jua,!0));(c=this.ha.toString())&&a.push("?",c);(c=this.Wa)&&a.push("#",s_9o(c,s_Kua));return a.join("")};
s_0o.prototype.resolve=function(a){var b=this.clone(),c=!!a.qa;c?s_1o(b,a.qa):c=!!a.Da;c?b.Da=a.Da:c=!!a.ka;c?s_2o(b,a.ka):c=null!=a.Ea;var d=a.ma;if(c)s_3o(b,a.Ea);else if(c=!!a.ma){if("/"!=d.charAt(0))if(this.ka&&!this.ma)d="/"+d;else{var e=b.ma.lastIndexOf("/");-1!=e&&(d=b.ma.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(s_gb(e,"./")||s_gb(e,"/.")){for(var d=s_9a(e,"/"),e=e.split("/"),f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):".."==k?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?s_4o(b,d):c=""!==a.ha.toString();c?s_5o(b,a.ha.clone()):c=!!a.Wa;c&&s_6o(b,a.Wa);return b};s_0o.prototype.clone=function(){return new s_0o(this)};
var s_1o=function(a,b,c){a.qa=c?s_7o(b,!0):b;a.qa&&(a.qa=a.qa.replace(/:$/,""));return a},s_2o=function(a,b,c){a.ka=c?s_7o(b,!0):b;return a},s_3o=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("sa`"+b);a.Ea=b}else a.Ea=null},s_4o=function(a,b,c){a.ma=c?s_7o(b,!0):b;return a},s_5o=function(a,b,c){b instanceof s_8o?(a.ha=b,s_Lua(a.ha,a.Ca)):(c||(b=s_9o(b,s_Mua)),a.ha=new s_8o(b,0,a.Ca));return a};s_0o.prototype.getQuery=function(){return this.ha.toString()};
s_0o.prototype.$=function(a,b){this.ha.set(a,b);return this};
var s_$o=function(a,b,c){s_la(c)||(c=[String(c)]);s_Nua(a.ha,b,c)},s_ap=function(a,b){return a.ha.get(b)},s_6o=function(a,b,c){a.Wa=c?s_7o(b):b;return a},s_bp=function(a,b){return a instanceof s_0o?a.clone():new s_0o(a,b)},s_Oua=function(a,b,c,d,e,f){var g=new s_0o(null,void 0);a&&s_1o(g,a);b&&s_2o(g,b);c&&s_3o(g,c);d&&s_4o(g,d);e&&s_5o(g,e);f&&s_6o(g,f);return g},s_7o=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},s_9o=function(a,b,c){return s_na(a)?(a=encodeURI(a).replace(b,
s_Pua),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},s_Pua=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},s_Hua=/[#\/\?@]/g,s_Jua=/[\#\?:]/g,s_Iua=/[\#\?]/g,s_Mua=/[\#\?@]/g,s_Kua=/#/g,s_8o=function(a,b,c){this.ka=this.$=null;this.ha=a||null;this.ma=!!c},s_cp=function(a){a.$||(a.$=new s_td,a.ka=0,a.ha&&s_Fua(a.ha,function(b,c){a.add(s_eb(b),c)}))},s_Qua=function(a){var b=s_Dba(a);if("undefined"==typeof b)throw Error("Bd");var c=new s_8o(null,0,void 0);
a=s_Oc(a);for(var d=0;d<b.length;d++){var e=b[d],f=a[d];s_la(f)?s_Nua(c,e,f):c.add(e,f)}return c};s_a=s_8o.prototype;s_a.ze=function(){s_cp(this);return this.ka};s_a.add=function(a,b){s_cp(this);this.ha=null;a=s_dp(this,a);var c=this.$.get(a);c||this.$.set(a,c=[]);c.push(b);this.ka+=1;return this};s_a.remove=function(a){s_cp(this);a=s_dp(this,a);return s_wd(this.$,a)?(this.ha=null,this.ka-=this.$.get(a).length,this.$.remove(a)):!1};s_a.clear=function(){this.$=this.ha=null;this.ka=0};
s_a.isEmpty=function(){s_cp(this);return 0==this.ka};var s_Rua=function(a,b){s_cp(a);b=s_dp(a,b);return s_wd(a.$,b)};s_a=s_8o.prototype;s_a.Us=function(a){var b=this.Xc();return s_Ib(b,a)};s_a.Pf=function(){s_cp(this);for(var a=this.$.Xc(),b=this.$.Pf(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};s_a.Xc=function(a){s_cp(this);var b=[];if(s_na(a))s_Rua(this,a)&&(b=s_Ob(b,this.$.get(s_dp(this,a))));else{a=this.$.Xc();for(var c=0;c<a.length;c++)b=s_Ob(b,a[c])}return b};
s_a.set=function(a,b){s_cp(this);this.ha=null;a=s_dp(this,a);s_Rua(this,a)&&(this.ka-=this.$.get(a).length);this.$.set(a,[b]);this.ka+=1;return this};s_a.get=function(a,b){a=a?this.Xc(a):[];return 0<a.length?String(a[0]):b};var s_Nua=function(a,b,c){a.remove(b);0<c.length&&(a.ha=null,a.$.set(s_dp(a,b),s_Pb(c)),a.ka+=c.length)};
s_8o.prototype.toString=function(){if(this.ha)return this.ha;if(!this.$)return"";for(var a=[],b=this.$.Pf(),c=0;c<b.length;c++)for(var d=b[c],e=s_db(d),d=this.Xc(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+s_db(d[f]));a.push(g)}return this.ha=a.join("&")};s_8o.prototype.clone=function(){var a=new s_8o;a.ha=this.ha;this.$&&(a.$=this.$.clone(),a.ka=this.ka);return a};
var s_dp=function(a,b){b=String(b);a.ma&&(b=b.toLowerCase());return b},s_Lua=function(a,b){b&&!a.ma&&(s_cp(a),a.ha=null,a.$.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),s_Nua(this,c,a))},a));a.ma=b};s_8o.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)s_Eba(arguments[b],function(a,b){this.add(b,a)},this)};

s_D("sy153");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy147");
s_D("sy147");s_F();
}catch(e){_DumpException(e)}
try{
s_E("lu");var s_l2c=["luibli","luibbri"],s_m2c={},s_WY=-1,s_n2c=null,s_o2c=function(a,b,c){a=a.cloneNode(!0);var d,e;b.hasAttribute("data-mh")&&(d=b.getAttribute("data-mh"));b.hasAttribute("data-mw")?e=b.getAttribute("data-mw"):e=88*c-16;var f;"IMG"==a.tagName?f=a:f=a.getElementsByTagName("IMG")[0];f.id="";f.width=e;void 0!==d&&(f.height=d);f.onload=function(){f.style.display="block";delete f.onload};f.style.display="none";c=f.src.split("&")[0]+"&w="+e;void 0!==d&&(c+="&h="+d);f.src=c;null!=f.parentNode&&(f.parentNode.style.width=
e+"px",void 0!==d&&(f.parentNode.style.height=d+"px"));b.appendChild(a)},s_p2c=function(a){if(!a)return null;var b,c=0,d;for(d in a)if(d=Number(d),0<a[d].offsetHeight){b=a[d];c=d;break}if(!b)return null;if(!b.firstChild){var e;for(d in a)if(d=Number(d),a[d].firstChild){e=a[d];break}s_o2c(e.firstChild,b,c)}return{element:b,wFa:c}},s_s2c=function(){for(var a=s_q2c(),b=!1,c=0;c<s_l2c.length;c++)for(var d=s_s(s_l2c[c]),e=0;e<d.length;e++)s_r2c(d[e])&&(b=!0);return a||b},s_q2c=function(){var a=s_q("rhs_block");
if(!a||0==a.offsetHeight)return!1;a:{for(var b={},c=3;5>=c;c++)if(b[c]=a.querySelector(".rhsmap"+c+"col"),b[c])b[c].column_count=c;else{a=null;break a}a=b}b=s_p2c(a);if(!b)return!1;a=b.wFa;if(s_WY==a&&s_m2c[s_WY])return!0;b=b.element.getElementsByTagName("IMG")[0];b.id||(s_q("lu_map").id="",b.id="lu_map");s_m2c[a]||(s_m2c[a]=!0);s_WY=a;return!0},s_r2c=function(a){for(var b=[],c,d="1"==a.getAttribute("data-crop"),e="1"==a.getAttribute("data-contain"),f=3;5>=f;f++){var g=a.querySelector(".luib-"+f);
if(!g)return!1;g=g.querySelector(".thumb");if(!g)return!1;b.push(g);0<g.offsetHeight&&(c=g)}if(!c)return!1;var k=parseInt(c.style.width,10),g=parseInt(c.style.height,10);if((f=c.querySelector("img"))&&f.src)return!0;for(var l,m,f=0;f<b.length;f++){var n=b[f].querySelector("img");if(n&&n.src){l=s_u("DIV");l.innerHTML=b[f].innerHTML;e&&(l.style.backgroundColor=b[f].style.backgroundColor);m=n;break}}if(!m)return!1;b=l.querySelector("img");d||e||(b.width=k,b.height=g,m=s_bp(m.src),m.$("w",parseInt(k,
10)),m.$("h",parseInt(g,10)),b.src=m.toString());c.innerHTML=l.innerHTML;d&&(b=c.querySelector("img"),d=(k-b.width)/2+"px",s_2e(a)?b.style.right=d:b.style.left=d,b.style.top=(g-b.height)/2+"px");e&&(b=c.querySelector("img"),c.style.backgroundColor=l.style.backgroundColor,l=Math.min(c.offsetHeight/b.height,c.offsetWidth/b.width),e=b.width*l,l*=b.height,b.width=e,b.height=l,b.style.top=(c.offsetHeight-l)/2+"px",d=(c.offsetWidth-e)/2+"px",s_2e(a)?b.style.right=d:b.style.left=d);return!0}; s_wf("lu",{init:function(){"webhp"!=google.sn&&s_q("lu_map")&&(s_s2c()?(s_n2c=s_tf(null,s_s2c,!0),s_pf(60,s_n2c)):(s_WY=3,s_m2c[s_WY]=!0))},dispose:function(){s_n2c&&(s_qf(60,s_n2c),s_n2c=null);s_m2c={};s_WY=-1}});

s_D("lu");s_F();
}catch(e){_DumpException(e)}
try{
var s_7Od={};s_E("m");var s_s5=null;var s_8Od,s_9Od,s_$Od,s_aPd,s_bPd,s_t5,s_cPd={},s_u5=null,s_v5=null,s_w5=[],s_ePd=function(){s_s5.ab.on&&(s_pf(41,s_dPd),s_pf(37,function(a){a&&(a=s_q("appbar"))&&(a.style.visibility="hidden")}),s_q("pocs"))},s_fPd=function(){return s_q("sftab")||s_q("lst-ib")},s_gPd=function(){var a=s_fPd();a&&s_l(a,"lst-d-f")},s_hPd=function(){var a=s_fPd();a&&s_m(a,"lst-d-f")},s_iPd=function(a){this.element=a;this.$=[];this.ka=null;"ab_opt"==this.element.id&&0==this.element.childNodes.length&&gbar.aomc(this.element);
a=s_s("ab_dropdownitem",this.element);for(var b=0,c;c=a[b];b++)s_k(c,"disabled")||this.$.push(c)},s_kPd=function(a){var b=s_u5;s_jPd(b,null==b.ka?a?0:b.$.length-1:(b.ka+(a?1:b.$.length-1))%b.$.length)},s_jPd=function(a,b){var c=a.$[b];c&&(s_lPd(a),s_l(c,"selected"),c.setAttribute("aria-selected","true"),c=c.querySelector("a, .action-menu-button")||c,c.setAttribute("tabindex","0"),c.focus(),a.ka=b)},s_lPd=function(a){var b=a.$[a.ka];b&&(s_m(b,"selected"),b.setAttribute("aria-selected","false"),(b.querySelector("a, .action-menu-button")||
b).setAttribute("tabindex","-1"),a.element.focus(),a.ka=null)};s_iPd.prototype.kd=function(a){for(var b=0,c;c=this.$[b];b++)if(a==c){b!=this.ka&&s_jPd(this,b);break}};
var s_nPd=function(a){var b=(a=s_pe(a,"ab_button"))&&s_v5!=a;s_u5&&s_x5();a&&b&&s_mPd(a)},s_oPd=function(a){google.ac&&google.ac.cc&&google.ac.cc();s_Cf(a.href);return!0},s_pPd=function(a,b,c){32==c.keyCode&&s_Cf(a.href)},s_qPd=function(a){s_z(s_q("ufp"),"block");s_nPd(a)},s_mPd=function(a,b){var c;c=s_ra(a);if(void 0==s_cPd[c]){var d;d=s_pe(a,"ab_ctl");var e=null;d&&(d=s_t("ab_dropdown",d))&&(e=new s_iPd(d));s_cPd[c]=e}if(c=s_cPd[c])s_l(a,"selected"),a.setAttribute("aria-expanded","true"),s_v5=a,
c.element.style.visibility="inherit",s_u5=c,c=a.id.indexOf("am-b"),a.id&&-1!=c&&(c=s_he(a))&&s_k(c,"action-menu")&&(c=s_t("action-menu-panel",c))&&s_B(a,[c],[],"","&id="+a.id),s_ta(document.body,"click",s_x5),s_ta(document.body,"keydown",s_rPd),b&&s_kPd(!0)},s_x5=function(a){s_u5&&((a=a||window.event)&&"click"==a.type&&s_pe(s_rf(a),"ab_button")&&(s_sf(a),a.preventDefault?a.preventDefault():a.returnValue=!1),s_ua(document.body,"click",s_x5),s_ua(document.body,"keydown",s_rPd),s_lPd(s_u5),s_u5.element.style.visibility=
"hidden",s_u5=null);s_v5&&(s_m(s_v5,"selected"),s_v5.setAttribute("aria-expanded","false"),s_v5=null)},s_rPd=function(a){27==a.keyCode&&s_x5()},s_sPd=function(a,b,c){if(9==c.keyCode)s_x5();else if(27==c.keyCode){if(s_u5)return s_x5(),s_y5(c)}else{if(38==c.keyCode||40==c.keyCode)return s_u5?s_kPd(40==c.keyCode):s_mPd(a,!0),s_y5(c);if(37==c.keyCode||39==c.keyCode)return s_y5(c)}return!0},s_tPd=function(a,b,c){s_u5&&((a=s_pe(s_rf(c),"ab_dropdownitem"))?s_u5.kd(a):s_lPd(s_u5))},s_uPd=function(){s_u5&&
s_lPd(s_u5)},s_vPd=function(a,b,c){if(s_u5)if(9==c.keyCode)s_x5();else{if(27==c.keyCode)return a=s_v5,s_x5(),a.focus(),s_y5(c);if(38==c.keyCode)return s_kPd(!1),s_y5(c);if(40==c.keyCode)return s_kPd(!0),s_y5(c);if(32==c.keyCode||37==c.keyCode||39==c.keyCode)return s_y5(c)}return!0},s_y5=function(a){s_sf(a);a.preventDefault&&a.preventDefault();return a.returnValue=!1},s_wPd=function(a){return s_Dc()?(37!=a.keyCode&&38!=a.keyCode&&39!=a.keyCode&&40!=a.keyCode||s_y5(a),!1):!0},s_dPd=function(a){var b=
s_q("rcnt"),c=s_Ij();if(c&&b){var d=parseInt(s_Ie(c,"top"),10),e=s_fPd(),e=e?e.offsetHeight:c.offsetHeight,b=s_Te(b);if(a!=s_8Od||d!=s_9Od||e!=s_$Od||b!=s_aPd){s_8Od=a;s_9Od=d;s_$Od=e;s_aPd=b;var d=0,f;if(f=a)f=!s_7Od.isch;f&&(c=s_Te(c)+e,d=Math.max(0,a+7-b+c));s_bPd=d}(a=s_q("center_col"))&&a.style.paddingTop!=s_bPd+"px"&&(a.style.paddingTop=s_bPd+"px")}return!1},s_xPd=function(){var a=s_q("bbar");a&&s_z(a,!1)},s_yPd=function(a){s_t5&&s_t5.remove("bbh");s_Cf(a.href)};
var s_zPd=!1;
s_wf("m",{init:function(a){s_s5=a;s_zPd||s_ePd();s_zPd=!0;s_fPd()&&(a=s_q("lst-ib"),s_ta(a,"focus",s_gPd),s_ta(a,"blur",s_hPd),a==s_qe(document)&&s_gPd());s_t5=s_Aj("local","abar");s_w5=[];(a=s_q("abar_ps_on"))&&s_w5.push(new s_r5(a,s_k(a,"disabled")?s_s5.msgs.sPersD:s_s5.msgs.sPers));(a=s_q("abar_ps_off"))&&s_w5.push(new s_r5(a,s_k(a,"disabled")?s_s5.msgs.hPersD:s_s5.msgs.hPers));a=s_t5?s_t5.get("bbh"):"";var b=document.getElementById("safesearch");"1"==a||b&&!b.getAttribute("data-safesearch-on")||!(a=
document.getElementById("bbar"))||(s_x(a,"visibility","hidden"),s_z(a,!0),b=s_y(a),s_x(a,"margin-left",-Math.floor(b.width/2)+"px"),s_x(a,"visibility","visible"),s_t5&&s_t5.set("bbh",1));s_Zh("m",{cc:s_oPd,hbke:s_sPd,hdke:s_vPd,hdhne:s_tPd,hdhue:s_uPd,go:s_pPd,mskpe:s_wPd,tdd:s_nPd,tei:s_qPd,hbb:s_xPd,cbbl:s_yPd},!0);s_Zh("ab",{cc:s_oPd,hbke:s_sPd,hdke:s_vPd,hdhne:s_tPd,hdhue:s_uPd,go:s_pPd,mskpe:s_wPd,tdd:s_nPd,tei:s_qPd,hbb:s_xPd,cbbl:s_yPd},!0)},dispose:function(){if(s_fPd()){var a=s_q("lst-ib"); s_ua(a,"focus",s_gPd);s_ua(a,"blur",s_hPd)}s_u5&&s_x5();s_cPd={};for(a=0;a<s_w5.length;a++)s_w5[a].destroy();s_w5=[];s_0h("ab","cc hbke hdke hdhne hdhue go mskpe tdd tei tne".split(" "))}});

s_D("m");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sf");s_wf("sf",{init:function(){s_Zh("sf",{chk:function(a){a.checked=!0},lck:function(a){a.form.q.value?a.checked=!0:s_ic().href="/doodles/"},tia:function(a,b){a=s_u("SCRIPT",{src:b.js});s_kf(a)}})}});
s_D("sf");s_F();
}catch(e){_DumpException(e)}
try{
var s_Ora=!1;s_E("vm");s_wf("vm",{init:function(a){s_Ora?"bv"in a&&(a=a.bv,s_xa=a>s_wa?1:a<s_wa?2:0,s_ya=!0):(s_Ora=!0,"bv"in a&&(s_wa=a.bv),s_xa=0,"d"in a&&(s_naa=a.d),"tc"in a&&(s_oaa=a.tc),"te"in a&&(s_paa=a.te),"ts"in a&&(s_qaa=a.ts),"tk"in a&&(s_raa=a.tk))}});
s_D("vm");s_F();
}catch(e){_DumpException(e)}
try{
var s_1i=function(a,b,c,d,e){d=d||("string"==typeof b?"":s_Fe(b));e=e||("string"==typeof c?"":s_Fe(c));a.Ef.push({bq:d,targetElement:b,mW:e,pda:c,oC:2})},s_2i=function(a,b,c){a=a.querySelectorAll('[jsaction^="'+b+':"], [jsaction*=";'+b+':"], [jsaction*=" '+b+':"]');for(var d=0;d<a.length;++d){var e=a[d],f;a:{f=e;for(var g=a,k=0;k<g.length;++k){var l=g[k];if(l!=f&&s_kga(l,f)){f=!0;break a}}f=!1}f||s_Qh(e,b,c)}},s_3i=function(a){return s_c(a.lastElementChild)?a.lastElementChild:s_3ca(a.lastChild,!1)},
s_pja=function(a){if(!arguments.length)return[];for(var b=[],c=arguments[0].length,d=1;d<arguments.length;d++)arguments[d].length<c&&(c=arguments[d].length);for(d=0;d<c;d++){for(var e=[],f=0;f<arguments.length;f++)e.push(arguments[f][d]);b.push(e)}return b};s_E("sy50");
var s_V=function(a){a=a.XM;var b=a.rootElement;b||(b=a.rootElement=s_t(a.uN));return b},s_qja=function(a){for(;!a.VCa;)if(a=a.parentElement,!a)return null;return a.VCa},s_5i=function(a){a=s_V(a);s_4i(a)},s_4i=function(a){(a=s_qja(a))&&a.render()},s_6i=function(a,b,c,d){s_Qh(s_V(a),b,c,d)},s_rja=function(a){a=s_rc(a);for(var b=0,c=a.length;b<c;b++){var d=a[b];if(s_9a(d,"r-"))return d.substring(2)}return null},s_sja=function(a){a=s_rja(a);s_Cha(a,!0)},s_7i=function(a){if(a){var b=a.__ctx;return b?b.bP()|| null:(a=s_rja(a))?s_Cha(a):null}return null},s_8i=function(a){var b=a.__ctx;if(b)return(a=b.bP())?s_p(a):s_Kd(null);(a=s_rja(a))?(a=s_ei.$[a]||null)?(a.controller||s_Bha(a),a.pQ||(a.pQ=s_Md(),s_Iga(a)),a=a.pQ.$):a=s_Kd(null):a=s_Kd(null);return a};

s_D("sy50");s_F();
}catch(e){_DumpException(e)}
try{
var s_tja=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d},s_uja=function(a,b){return a.left<=b.left+b.width&&b.left<=a.left+a.width&&a.top<=b.top+b.height&&b.top<=a.top+a.height},s_9i=function(a){return new s_Jd(function(b){var c=a.length,d=[];if(c)for(var e=function(a,e,f){c--;d[a]=e?{$sa:!0,value:f}:{$sa:!1,reason:f};0==c&&b(d)},f=0,g;f<a.length;f++)g=a[f],s_Hca(g,s_f(e,f,!0),s_f(e,f,!1));else b(d)})},s_vja=function(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<
b?-1:a==b?0:1},s_$i=function(a){if(!a.getBoundingClientRect)return null;a=s_zda(s_uda,a);return new s_Da(a.right-a.left,a.bottom-a.top)},s_wja=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],g=arguments[b];g;)f.unshift(g),g=g.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){for(var g=d[0][b],k=1;k<c;k++)if(g!=d[k][b])return f;f=g}return f},s_xja=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
s_yja=function(a){if(a.__ctx)return null;a=(a=s_rja(a))?(a=s_ei.$[a]||null)?a.dom:null:null;return a},s_aj=function(a,b){return a==b||!(!a||!b)&&a instanceof b.constructor&&s_$fa(a.Oa(),b.Oa())},s_bj=function(a){return Array.prototype.join.call(arguments,"")},s_zja=function(a,b,c){var d=0;return function(e){s_ga.clearTimeout(d);var f=arguments;d=s_ga.setTimeout(function(){a.apply(c,f)},b)}},s_Aja=function(a,b){try{s_va(a,b,void 0)}catch(c){}};s_E("sy51");
var s_W=function(a){this.Ga=a;this.Da=a.XM.Yo||""};s_W.prototype.Va=function(){return s_V(this.Ga)};var s_Bja=function(a,b,c){b="."+a.Da+"-"+b;c&&(b+=",."+a.Da+"-"+c);return b},s_X=function(a,b,c){return a.Va().querySelector(s_Bja(a,b,c))},s_cj=function(a,b,c){return a.Va().querySelectorAll(s_Bja(a,b,c))},s_Y=function(a,b){return(a=s_X(a,b,void 0))?s_8i(a):s_Kd(null)};s_W.prototype.AY=function(a){return(a=s_X(this,a,void 0))&&s_7i(a)}; var s_dj=function(a,b){var c=[];s_j(s_cj(a,b,void 0),function(a){c.push(s_8i(a))},a);return c};

s_D("sy51");s_F();
}catch(e){_DumpException(e)}
try{
s_E("sy386");var s_QD=function(a){s_I(this,a,0,26,null,null)};s_h(s_QD,s_H);s_QD.prototype.Yh=function(){return s_(this,2)};s_QD.prototype.ll=function(a){s_M(this,2,a)};s_QD.prototype.getId=function(){return s_(this,5)};s_QD.prototype.Qd=function(a){s_M(this,5,a)};var s_RD=function(a){s_I(this,a,0,-1,null,null)};s_h(s_RD,s_H);s_RD.prototype.ZK=function(){return s_(this,1)};s_RD.prototype.k8=function(a){s_M(this,1,a)};
var s_Lkb=function(a,b,c,d){var e={};e.g=a.toString();e.p=b.toString();e.m=c.toString();null!=d&&(e.u=d.toString());return s_mk("promos",e,"jspb")},s_Okb=function(a,b){var c=s_Mkb("OGP")||"";s_Nkb("OGP",c+("-"+a+":"),b)},s_Qkb=function(a,b,c,d){if(5==c){var e=s_Pkb(a)+1;b=new RegExp("\\b"+a+"-([0-9]+):");var f=(c=s_Mkb("OGPC"))&&c.match(b);a=a+"-"+e+":";a=f?c.replace(b,a):(c||"")+a;s_Nkb("OGPC",a,d)}else 2==c&&(d={},d.g=a.toString(),d.p=b.toString(),d.m="i",d.ic=(1).toString(),s_mk("promos",d,"jspb"))},
s_Pkb=function(a){if(!s_4f())return 0;var b=s_Mkb("OGPC");return b?(a=b.match(new RegExp("\\b"+a+"-([0-9]+):")))&&a[1]?parseInt(a[1],10):0:0},s_Nkb=function(a,b,c){if(s_4f()){var d=s_Rkb();s_2f.set(a,b,!c||-2==c||31536E3<c?31536E3:c,"/",d)}},s_Mkb=function(a){return s_4f()?s_2f.get(a)||null:null},s_Rkb=function(){var a=s_ac(s_bc(3,s_kc())).match("google(?:.[a-z]{2,3}){1,2}$");return a?a[0]:null};
var s_SD=function(a,b,c){this.$=a;this.ka=b;this.ha=c;this.ma=s_Rkb()};s_SD.prototype.log=function(a,b,c){c=c||1;var d=s_Qua({ogsr:Math.round(1/c),id:this.ka,ic:s_Pkb(this.$),ogd:this.ma,ogprm:"up"}).toString();b&&("&"!=b.charAt(0)&&(b="&"+b),d+=b);Math.random()<c&&google.log(this.ha.toString(),a+"&"+d)};var s_Tkb=function(a,b){return s_Skb(b||null,a,1)},s_Skb=function(a,b,c){var d="";if(b){var d=new s_$e,e=s_Fe(b);b=a?a:b;0==c?s_af(d,e,b):s_bf(d,e,b);d=s_df(d)}a&&(d+="&ved="+s_Fe(a));return d};

s_D("sy386");s_F();
}catch(e){_DumpException(e)}
try{
s_E("mids");var s_a5c=function(a,b){this.qa=b.Va();this.$=a.$.get("group_id");this.ha=a.$.get("promo_id");this.ma=a.$.get("dismissal_type");a=a.$.get("payload_type");this.Bd=new s_SD(this.$,this.ha,a);s_Qkb(this.$,this.ha,this.ma);this.Bd.log("i","ved="+s_Fe(this.qa),1)};s_h(s_a5c,s_i);
var s_b5c=function(a){this.$=a},s_c5c=function(a){s_W.call(this,a)};s_h(s_c5c,s_W);s_U(function(a){s_T(a,"t-Gza07Ho9En4",s_a5c,s_b5c,s_c5c,function(a,c,d){s_a5c.call(a,c,d)})});
s_D("mids");s_F();
}catch(e){_DumpException(e)}
// Google Inc.
